apiVersion: v1
kind: Pod
metadata:
  name: example-tools-regular
spec:
  containers:
    - name: example-tools-regular
      image: registry.redhat.io/rhel8/support-tools
      command: ["/bin/bash", "-c", "sleep 99999999999"]
