apiVersion: v1
kind: Pod
metadata:
  name: example-fedora-regular
spec:
  containers:
    - name: example-fedora-regular
      image: registry.fedoraproject.org/fedora
      ports:
        - containerPort: 8080
      command: ["python3"]
      args: [ "-m", "http.server", "8080"]
