apiVersion: v1
kind: Pod
metadata:
  name: example-tools-regular-2
spec:
  securityContext:
    runAsUser: 0
  containers:
    - name: example-tools-regular
      image: registry.redhat.io/rhel8/support-tools
      command: ["/bin/bash", "-c", "sleep 99999999999"]
      securityContext:
        capabilities:
          add: ["NET_ADMIN", "SYS_TIME"]
